### ISSUE TITLE
How does one get a dump of their system image?

### ISSUE THREAD

**Issue by Viktor-913** [JSCU-NL/COATHANGER#1]
Can you add instructions on how to get a dump of the system image.

Thanks.

**Comment by JSCU-CNI** [comment]
Hi @Viktor-913. Thank you for your question.

If you are running a FortiGate VM you can pass a virtual configuration or disk file (e.g. `*.vmx` or `*.vmdk`) to the `coathanger.py` script directly. Dissect will work it's magic and you will not need a separate disk image in this instance.

If you have a physical appliance you will mainly have to rely on live forensic triage. Our [advisory](https://www.ncsc.nl/documenten/publicaties/2024/februari/6/mivd-aivd-advisory-coathanger-tlp-clear) contains triage commands which allows you to perform live forensics (on both physical appliances and virtual machines) when logged in to the CLI via the web interface, TTY or SSH.

Note that the script only implements a subset of the detection methods described in the advisory. It should therefore only be used as an addition to the (live forensics) methods described in the advisory.

If you would like to create a disk image of your physical appliance, you should contact your FortiNet representative for assistance.

**Comment by davidbudriss** [comment]
I have contacted Fortinet support and they do not support creating a disk image of the physical appliance.
